version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: submission-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_submission_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - submission-network

volumes:
  mysql_data:

networks:
  submission-network: