services:
  mysql:
    restart: always

  redis:
    restart: always

  config-server:
    restart: always

  discovery-server:
    restart: always

  auth-service:
    restart: always

  problem-service:
    restart: always

  attempt-service:
    restart: always

  question-service:
    restart: always

  quiz-service:
    restart: always

  user-service:
    restart: always

  submission-service:
    restart: always

  result-service:
    restart: always

  api-gateway:
    restart: always

  rankx-web:
    restart: always

  rankx-admin:
    restart: always
