spring.application.name=auth-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.jpa.open-in-view=false
##security.jwt.secret=${SECURITY_JWT_SECRET:cmFua3gtbG9jYWwtZG9ja2VyLXNlY3JldC1mb3Itand0LTIwMjY=}
