spring.application.name=problem-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=create-drop



